version: '3.1'

services:
  users_api:

    image: web

    build:
      context: ./
      dockerfile: Dockerfile

    container_name: users_api_cp

    ports:
      - "80:4000"

    expose:
      - '80'

    volumes:
      - ./src:/src

    working_dir: /src
